services:

  echo-server:
    image: "romanowalex/echo-server:v2.0"
    container_name: echo-server
    environment:
      SPRING_PROFILES_ACTIVE: simple
    networks:
      - network1
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:8080/manage/health" ]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.54.1
    networks:
      - network1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: grafana
    image: grafana/grafana:9.5.2
    restart: unless-stopped
    volumes:
    - ./grafana/provisioning:/etc/grafana/provisioning
    - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
     - GF_AUTH_BASIC_ENABLED=false
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH:="/var/lib/grafana/dashboards/10280_rev1.json"
    networks:
      - network1
    ports:
      - "3000:3000"

networks:
  network1:
    enable_ipv6: false
    driver: bridge