global:
  scrape_interval: 5s

scrape_configs:
  - job_name: backend
    scrape_interval: 30s
    metrics_path: '/manage/prometheus'
    scheme: http
    static_configs:
      - targets: [echo-server:8080]